# Generated by Django 6.1.1 on 2026-09-23 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtarefa',
            name='status',
            field=models.CharField(default='a fazer', max_length=20),
        ),
    ]
